spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/train?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    cache: false
  messages:
    basename: i18n.message

  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret:
    key: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjMiLCJ1c2VySWQiOjEsInVzZXJSb2xlIjoidXNlciIsImV4cCI6OTk5OTk5OTk5OX0.4t_FqZz0-6Q4Z7b8X7wV9J6Y8rX7wV9J6Y8rX7wV9J6Y8rX7wV9J6Y8rX7wV9J6Y8rX7wV9J6Y8rX7wV9J6Y8rX7
#mybatis-plus:
#  type-aliases-package: com.qdu.entity
#  mapper-locations: classpath:com.qdu.mapper/*Mapper.xml
##  configuration:
##    map-underscore-to-camel-case: true
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志
#
mybatis-plus:
  mapper-locations: classpath:com.qdu.mapper/*Mapper.xml
  type-aliases-package: com.qdu.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: true
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  extension:
    enabled: true
    data-permission:
      enabled: true
